healthyhams.Web/Models/JournalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;
using healthyhams.Data.Models;

namespace healthyhams.Web.Models
{
    public class JournalViewModel
    {
        public int UserHistoryId { get; set; }

        public int UserInformationId { get; set; }

        [Display(Name = "Select date:")]
        [Required(ErrorMessage = "Date is required.")]
        public DateTime JournalDate { get; set; }

        [Display(Name = "Serving size (g):")]
        [Required(ErrorMessage = "Serving size is required.")]
        [Range(0, int.MaxValue)]
        public int ServingSize { get; set; }

        [Display(Name = "Food name:")]
        [Required(ErrorMessage = "Food name is required.")]

        public int FoodId { get; set;}
        public string FoodName { get; set; }
        public int Calories { get; set; }
        public double Protein { get; set; }
        public double Carbs { get; set; }
        public double Fat { get; set; }



    }

}

//public string SearchTerm { get; set; }
//public Food Food { get; set; }
//public UserInformation UserInformation { get; set; }

//public UserHistory UserHistory { get; set; }

healthyhams.Web/Controllers/MyRecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using healthyhams.Data.Services;
using healthyhams.Data;
using System.Collections;
using healthyhams.Web.Models;
using System.Web.WebPages;
using healthyhams.Data.Models;
using System.Security.Permissions;
using Microsoft.Ajax.Utilities;
using System.Web.Http.Results;
using System.Data.Entity;
using System.Collections.ObjectModel;
using System.Xml.Linq;

namespace healthyhams.Web.Controllers
{
    public class MyRecipesController : Controller
    {
        private readonly IFoodData db;

        private readonly healthyhamsContext context;

        public MyRecipesController(IFoodData db, healthyhamsContext context)
        {
            this.db = db;
            this.context = context;

        }

        // GET: MyRecipes
        public ActionResult Index()
        {
            var recipeData = getRecipeData();

            if(recipeData.Count == 0)
            {
                ViewBag.RecipeCount = 0;
            }
           

            return View(recipeData);

        }

        public ActionResult CreateRecipe()
        {

            //var ingredientsData = getIngredientsForARecipe(@Session["recipeName"].ToString());

            //var ingredients = Session["ingredientsForNewRecipe"];
            //ViewBag.RecipeName = name;
            //var ingredientsData = getLastRecipeIngredients(model);

            //return View(ingredientsData);

            return View();
        }

        public ActionResult _EditRecipe()
        {
            var recipeData = getRecipeData();

            return View(recipeData);
        }


        public ActionResult _CreateRecipeReadonly()
        {
            
            var ingredientsData = getIngredientsForARecipe(@Session["recipeName"].ToString());

            //var ingredients = Session["ingredientsForNewRecipe"];
            //ViewBag.RecipeName = name;
            //var ingredientsData = getLastRecipeIngredients(model);

            return View(ingredientsData);

            //var recipeData = getRecipeData();

            //return View(recipeData);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRecipe(string searchTerm, Recipe model)
        {
            if (!searchTerm.IsEmpty())
            {
                var food = context.Food.Where(x => x.FoodName.Equals(searchTerm)).ToList();

                if (food != null)
                {
                    ViewBag.SearchTerm = food;
                }

                if (food.Count == 0)
                {
                    var userId = Convert.ToInt32(Session["userId"]);
                    return View();
                }
                else
                {
                    var userId = Convert.ToInt32(Session["userId"]);

                    System.Web.HttpContext.Current.Session["foodRecipeId"] = food[0].FoodId;
                    var foodRecipeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["foodRecipeId"]);

                    System.Web.HttpContext.Current.Session["recipeName"] = model.RecipeName;

                    //var recipe = context.Recipe.Where(x => x.RecipeName.Equals(model.RecipeName)).ToList();

                    //if(recipe.Count > 0)
                    //{
                    //    ViewBag.RecipeAlreadyInDb = 1;

                    //}
                    if (ModelState.IsValid)
                    {
                        int recordsCreated = db.addRecipeDb(model.RecipeName, model.ServingSize, foodRecipeId, userId);

                        var ingredientData = getIngredientsForARecipe(model.RecipeName);

                        return View("_CreateRecipeReadonly", ingredientData);
                    }
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _CreateRecipeReadonly(string searchTerm, Recipe model)
        {
            if (!searchTerm.IsEmpty())
            {
                var food = context.Food.Where(x => x.FoodName.Equals(searchTerm)).ToList();

                if (food != null)
                {
                    ViewBag.SearchTerm = food;
                }

                if (food.Count == 0)
                {
                    var userId = Convert.ToInt32(Session["userId"]);
                    return View();
                }
                else
                {
                    var userId = Convert.ToInt32(Session["userId"]);

                    System.Web.HttpContext.Current.Session["foodRecipeId"] = food[0].FoodId;
                    var foodRecipeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["foodRecipeId"]);

                    System.Web.HttpContext.Current.Session["recipeName"] = model.RecipeName;

                    //var recipe = context.Recipe.Where(x => x.RecipeName.Equals(model.RecipeName)).ToList();

                    //if(recipe.Count > 0)
                    //{
                    //    ViewBag.RecipeAlreadyInDb = 1;

                    //}
                    if (ModelState.IsValid)
                    {
                        int recordsCreated = db.addRecipeDb(model.RecipeName, model.ServingSize, foodRecipeId, userId);

                        var ingredientData = getIngredientsForARecipe(model.RecipeName);

                        return View("_CreateRecipeReadonly", ingredientData);
                    }
                }
            }

            return View();
        }

        public ICollection getRecipeData()
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();

            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"]).GroupBy(x => x.RecipeName).Select(x => x.FirstOrDefault()).ToList();

            return ingredientsData;

        }

        public ICollection getIngredients()
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();


            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"]).GroupBy(x => x.RecipeName).Select(x => x).SelectMany(x => x).ToList();

            return ingredientsData;

        }

        public ICollection getIngredientsForARecipe(string nume)
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();


            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"] && x.RecipeName == nume).GroupBy(x => x.RecipeName).Select(x => x).SelectMany(x => x).ToList();

            return ingredientsData;

        }

        public ICollection getLastRecipeIngredients(Recipe model)
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,

healthyhams.Web/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System.Drawing;
using Syncfusion.Pdf.Grid;
using System.Data;
using healthyhams.Web.Models;
using System.Collections;
using healthyhams.Data.Services;
using healthyhams.Data;
using Microsoft.Ajax.Utilities;
using System.Data.SqlTypes;
using System.IO;

namespace healthyhams.Web.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly IUserData db;

        private readonly healthyhamsContext context;

        public StatisticsController(IUserData db, healthyhamsContext context)
        {
            this.db = db;
            this.context = context;
        }

        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreatePDFDocument(ReportViewModel model)
        {
            var data = getUserHistory(model.ReportStartDate, model.ReportEndDate);

            generatePdf();

            return RedirectToAction("Index");
        }

        public ICollection getUserHistory(DateTime startDate, DateTime endDate)
        {
            var query = context.UserHistory
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.JournalDate,
                          h.ServingSize,
                          h.FoodId,
                          h.UserHistoryId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new JournalViewModel
                    {
                        UserHistoryId = h.UserHistoryId,
                        UserInformationId = h.UserInformationId,
                        JournalDate = h.JournalDate,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();

            var historyData = query.Where(x => x.JournalDate >= startDate.Date && x.JournalDate <= endDate.Date && x.UserInformationId == (int)Session["userId"]).OrderBy(t => t.JournalDate).ToList();


            return historyData;

        }

        public void generatePdf()
        {
            //Create a new PDF document
            PdfDocument doc = new PdfDocument();
            //Add a page to the document
            PdfPage page = doc.Pages.Add();

            //Create PDF graphics for the page
            PdfGraphics graphics = page.Graphics;
            //Load the image from the disk
            FileStream imageStream = new FileStream("healthyhams-logo.png", FileMode.Open, FileAccess.Read);

            PdfBitmap image = new PdfBitmap(imageStream);
            //Draw the image
            graphics.DrawImage(image, new RectangleF(180, 15, 150, 100));

            //Creating the stream object
            MemoryStream stream = new MemoryStream();

            doc.Save(stream);
            doc.Save("Output.pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);

            //Close the document
            doc.Close(true);
        }
    }
}

healthyhams.Web/Views/Journal/Index.cshtml
@model IEnumerable<healthyhams.Web.Models.JournalViewModel>


@{
    ViewBag.Title = "Journal";
    int defaultQuantity = 100; // g
}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>


    <link rel="stylesheet" href="~/Content/css/Journal.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

    <script>
        $(function () {
            var availableTags = [];
            $.ajax(
                {
                    type: 'GET',
                    url: '/Journal/getAllFoods',
                    success: function (response) {
                        $.each(response, function (key, item) {
                            availableTags.push(item.FoodName)
                        });
                    }
                });

            $("#SearchTerm").autocomplete({
                source: availableTags
            });
        });

    </script>
</head>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("User", "Home")"><img src="~/Content/media/logo.png" alt="Logo" height="100" width="150" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("Journal", "Index", "Journal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My Recipes", "Index", "MyRecipes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Report", "Index", "Statistics", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Account", "Index", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <h1>My Journal</h1>
        <div class="form-horizontal journal-container">
            <div class="form-group row">
                <label for="JournalDate" name="JournalDate" class="control-label col-sm-3">Journal Date:</label>
                <div class="group">
                    <input type="date" name="JournalDate" id="JournalDate" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label for="SearchTerm" name="SearchTerm" class="control-label col-sm-3">Food Name:</label>
                <div class="group">
                    <input type="text" name="SearchTerm" id="SearchTerm" class="form-control" required />
                </div>
            </div>

            <div class="form-group row">
                <label for="ServingSize" name="ServingSize" class="control-label col-sm-3">Serving size (g):</label>

                <div class="group">
                    <input type="number" name="ServingSize" id="ServingSize" class="form-control" min="0" required />

                </div>
            </div>
            <input type="submit" value="Add Food" class="button" />

            @if (ViewBag.historyCount != 0)
            {
                <table class="table table-striped" id="food-table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Serving size(g)</th>
                            <th>Energy(kcal)</th>
                            <th>Protein</th>
                            <th>Carbs</th>
                            <th>Fat</th>
                        </tr>
                    </thead>



                    <tbody>

                        @if (ViewBag.SearchTerm != null)
                        {
                            if (ViewBag.SearchTerm.Count == 0)
                            {
                                <div class="alert alert-danger">The food you entered is not in the database. Search a food item that is stored in the database.</div>
                            }
                        }

                        @if (Model != null)
                        {
                            if (Model.Count() > 0)
                            {
                                var sumOfCalories = 0;
                                var sumOfProtein = 0;
                                var sumOfCarbs = 0;
                                var sumOfFat = 0;


                                foreach (var item in Model)
                                {
                                    ViewBag.UserId = item.UserInformationId;

                                    var calories = @item.ServingSize * @item.Calories / defaultQuantity;
                                    var protein = @item.ServingSize * @item.Protein / defaultQuantity;
                                    var carbs = @item.ServingSize * @item.Carbs / defaultQuantity;
                                    var fat = @item.ServingSize * @item.Fat / defaultQuantity;

                                    sumOfCalories += calories;
                                    sumOfProtein += (int)protein;
                                    sumOfCarbs += (int)carbs;
                                    sumOfFat += (int)fat;

                                    ViewBag.JournalDate = @item.JournalDate.ToShortDateString();

                                    <tr>
                                        <td>@item.JournalDate.ToShortDateString()</td>
                                        <td>@item.FoodName</td>
                                        <td>@item.ServingSize<span> g</span></td>
                                        <td>@calories<span> g</span></td>
                                        <td>@((int)protein)<span> g</span></td>
                                        <td>@((int)carbs)<span> g</span></td>
                                        <td>@((int)fat)<span> g</span></td>
                                        <td><input type="button" value="Edit" class="button-link" onclick="location.href='@Url.Action("Edit", "Journal", new { id = item.UserHistoryId })'" /></td>
                                        <td><input type="button" value="Delete" class="button-link" onclick="return confirm('Are you sure you wish to delete this item?'), location.href='@Url.Action("Delete", "Journal", new { id = item.UserHistoryId })'" /></td>
                                    </tr>

                                    ViewBag.SumOfCalories = sumOfCalories;
                                    ViewBag.SumOfProtein = sumOfProtein;
                                    ViewBag.SumOfCarbs = sumOfCarbs;
                                    ViewBag.SumOfFat = sumOfFat;
                                }

                            }
                        }

                    </tbody>
                </table>

                <h3 id="total-text">Total</h3>
                <table class="table table-striped total-table">
                    <thead>
                        <tr>
                            <th>Energy(kcal)</th>
                            <th>Protein</th>
                            <th>Carbs</th>
                            <th>Fat</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@ViewBag.SumOfCalories<span> g</span></td>
                            <td>@ViewBag.SumOfProtein<span> g</span></td>
                            <td>@ViewBag.SumOfCarbs<span> g</span></td>
                            <td>@ViewBag.SumOfFat<span> g</span></td>

                        </tr>
                    </tbody>
                </table>
            }

        </div>
    }
</body>

healthyhams.Web/Views/Journal/_EditJournal.cshtml
@model IEnumerable<healthyhams.Web.Models.JournalViewModel>
@{
    ViewBag.Title = "Journal";
    int defaultQuantity = 100; // g
}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>


    <link rel="stylesheet" href="~/Content/css/Journal.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

    <script>
        $(function () {
            var availableTags = [];
            $.ajax(
                {
                    type: 'GET',
                    url: '/Journal/getAllFoods',
                    success: function (response) {
                        $.each(response, function (key, item) {
                            availableTags.push(item.FoodName)
                        });
                    }
                });

            $("#SearchTerm").autocomplete({
                source: availableTags
            });
        });
    </script>
</head>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("User", "Home")"><img src="~/Content/media/logo.png" alt="Logo" height="100" width="150" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("Journal", "Index", "Journal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My Recipes", "Index", "MyRecipes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Report", "Index", "Statistics", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Account", "Index", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <table class="table table-striped" id="food-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Serving size(g)</th>
                    <th>Energy(kcal)</th>
                    <th>Protein</th>
                    <th>Carbs</th>
                    <th>Fat</th>
                </tr>
            </thead>

            <tbody>

                @if (ViewBag.SearchTerm != null)
                {
                    if (ViewBag.SearchTerm.Count == 0)
                    {
                        <div class="alert alert-danger">The food you entered is not in the database. Search a food item that is stored in the database.</div>
                    }
                }


                @if (Model != null)
                {
                    if (Model.Count() > 0)
                    {
                        foreach (var item in Model)
                        {
                            var calories = @item.ServingSize * @item.Calories / defaultQuantity;
                            var protein = @item.ServingSize * @item.Protein / defaultQuantity;
                            var carbs = @item.ServingSize * @item.Carbs / defaultQuantity;
                            var fat = @item.ServingSize * @item.Fat / defaultQuantity;

                            <tr>
                                <td>@item.JournalDate.ToShortDateString()</td>
                                <td>@item.FoodName</td>
                                @if (ViewBag.UserHistoryId != null && @item.UserHistoryId == ViewBag.UserHistoryId)
                                {
                                    <td><input type="number" name="ServingSize" id="ServingSize" min="0" /><span> g</span></td>

                                }
                                else
                                {
                                    <td>@item.ServingSize<span> g</span></td>
                                }
                                <td>@calories<span> g</span></td>
                                <td>@((int)protein)<span> g</span></td>
                                <td>@((int)carbs)<span> g</span></td>
                                <td>@((int)fat)<span> g</span></td>
                                <td><input type="submit" value="Save" class="button-link" /></td>
                                <td><input type="button" value="Cancel" class="button-link" onclick="location.href='@Url.Action("Index", "Journal")'"/></td>
                                @*<td>@Html.ActionLink("Cancel", "Index", new { id = item.UserHistoryId })</td>*@
                            </tr>

                        }
                    }
                }


            </tbody>
        </table>
    </div>
    }

    @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@


</body>