healthyhams.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using healthyhams.Data.Enums;

namespace healthyhams.Web.Models
{
    public class HomeViewModel
    {
        public string Category { get; set; }
    }
}

healthyhams.Web/Controllers/HomeController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Migrations.Model;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.Expressions;
using System.Windows.Media.Imaging;
using healthyhams.Data;
using healthyhams.Data.Enums;
using healthyhams.Data.Models;
using healthyhams.Data.Services;

namespace healthyhams.Web.Controllers
{
    public class HomeController : Controller
    {
        MealDbService _mealDb = new MealDbService();

        public ActionResult Index()
        {
            //var recipes = _mealDb.GetRecipies(Category.Seafood).GetAwaiter().GetResult();

            //foreach (RecipeApiModel recipe in recipes)
            //{
            //    //Console.WriteLine(recipe.Title);
            //    //ViewBag.RecipesfromApi = recipes;
            //    var recipePicture = (Bitmap)((new ImageConverter()).ConvertFrom(recipe.Picture));
            //    recipe.Picture = recipePicture;
            //}

            //return View(recipes);
            return View();
        }

        public ActionResult User()
        {
            //var categories = _mealDb.GetAllCategories().GetAwaiter().GetResult();

            //var ingredient = _mealDb.GetAllCategories().GetAwaiter().GetResult();

            return View();
        }

        public ActionResult Recipe(int id)
        {
            var recipeById = _mealDb.GetRecipeById(id).GetAwaiter().GetResult();

            return View(recipeById);
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            Session.Abandon();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult User(string searchTermCategory, string searchTermArea, string searchTermIngredient, string searchType, RecipeApiModel model)
        {
            var recipes = _mealDb.GetRecipiesByCategory(searchTermCategory, searchTermArea, searchTermIngredient, searchType).GetAwaiter().GetResult();

            if(recipes != null)
            {
                return View(recipes);
            }
            else
            {
                return View();
            }
            


        }


        public JsonResult getAllCategories()
        {
            var categories = _mealDb.GetAllCategories().GetAwaiter().GetResult();

            return Json(categories, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getAllAreas()
        {
            var areas = _mealDb.GetAllAreas().GetAwaiter().GetResult();

            return Json(areas, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getAllIngredients()
        {
            var ingredients = _mealDb.GetAllIngredients().GetAwaiter().GetResult();

            return Json(ingredients, JsonRequestBehavior.AllowGet);
        }

    }
}

healthyhams.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using healthyhams.Data.Services;
using healthyhams.Data;
using healthyhams.Web.Models;


namespace healthyhams.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserData db;

        private readonly healthyhamsContext context;

        public LoginController(IUserData db, healthyhamsContext context)
        {
            this.db = db;
            this.context = context;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(SignUpViewModel model)
        {
            var status = context.Credentials.Where(x => x.Email == model.Email && x.Password == model.Password).FirstOrDefault();
            if (status == null)
            {
                ViewBag.LoginStatus = 0;
            }
            else
            {
                int userId = context.Credentials.Where(x => x.Email == model.Email && x.Password == model.Password).FirstOrDefault().CredentialsId;
                string email = context.Credentials.Where(x => x.Email == model.Email && x.Password == model.Password).FirstOrDefault().Email;
                string password = context.Credentials.Where(x => x.Email == model.Email && x.Password == model.Password).FirstOrDefault().Password;

                Session["userId"] = userId;
                Session["userEmail"] = email;
                Session["userPassword"] = password;

                return RedirectToAction("User", "Home", new { id = userId });
            }

            return View();
        }
    }
}

healthyhams.Web/Controllers/MyRecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using healthyhams.Data.Services;
using healthyhams.Data;
using System.Collections;
using healthyhams.Web.Models;
using System.Web.WebPages;
using healthyhams.Data.Models;
using System.Security.Permissions;
using Microsoft.Ajax.Utilities;
using System.Web.Http.Results;
using System.Data.Entity;
using System.Collections.ObjectModel;
using System.Xml.Linq;

namespace healthyhams.Web.Controllers
{
    public class MyRecipesController : Controller
    {
        private readonly IFoodData db;

        private readonly healthyhamsContext context;

        public MyRecipesController(IFoodData db, healthyhamsContext context)
        {
            this.db = db;
            this.context = context;

        }

        // GET: MyRecipes
        public ActionResult Index()
        {
            var recipeData = getRecipeData();

            if(recipeData.Count == 0)
            {
                ViewBag.RecipeCount = 0;
            }
           

            return View(recipeData);

        }

        public ActionResult CreateRecipe()
        {

            //var ingredientsData = getIngredientsForARecipe(@Session["recipeName"].ToString());

            //var ingredients = Session["ingredientsForNewRecipe"];
            //ViewBag.RecipeName = name;
            //var ingredientsData = getLastRecipeIngredients(model);

            //return View(ingredientsData);

            return View();
        }

        public ActionResult _EditRecipe()
        {
            var recipeData = getRecipeData();

            return View(recipeData);
        }


        public ActionResult _CreateRecipeReadonly()
        {
            
            var ingredientsData = getIngredientsForARecipe(@Session["recipeName"].ToString());

            //var ingredients = Session["ingredientsForNewRecipe"];
            //ViewBag.RecipeName = name;
            //var ingredientsData = getLastRecipeIngredients(model);

            return View(ingredientsData);

            //var recipeData = getRecipeData();

            //return View(recipeData);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRecipe(string searchTerm, Recipe model)
        {
            if (!searchTerm.IsEmpty())
            {
                var food = context.Food.Where(x => x.FoodName.Equals(searchTerm)).ToList();

                if (food != null)
                {
                    ViewBag.SearchTerm = food;
                }

                if (food.Count == 0)
                {
                    var userId = Convert.ToInt32(Session["userId"]);
                    return View();
                }
                else
                {
                    var userId = Convert.ToInt32(Session["userId"]);

                    System.Web.HttpContext.Current.Session["foodRecipeId"] = food[0].FoodId;
                    var foodRecipeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["foodRecipeId"]);

                    System.Web.HttpContext.Current.Session["recipeName"] = model.RecipeName;

                    //var recipe = context.Recipe.Where(x => x.RecipeName.Equals(model.RecipeName)).ToList();

                    //if(recipe.Count > 0)
                    //{
                    //    ViewBag.RecipeAlreadyInDb = 1;

                    //}
                    if (ModelState.IsValid)
                    {
                        int recordsCreated = db.addRecipeDb(model.RecipeName, model.ServingSize, foodRecipeId, userId);

                        var ingredientData = getIngredientsForARecipe(model.RecipeName);

                        return View("_CreateRecipeReadonly", ingredientData);
                    }
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _CreateRecipeReadonly(string searchTerm, Recipe model)
        {
            if (!searchTerm.IsEmpty())
            {
                var food = context.Food.Where(x => x.FoodName.Equals(searchTerm)).ToList();

                if (food != null)
                {
                    ViewBag.SearchTerm = food;
                }

                if (food.Count == 0)
                {
                    var userId = Convert.ToInt32(Session["userId"]);
                    return View();
                }
                else
                {
                    var userId = Convert.ToInt32(Session["userId"]);

                    System.Web.HttpContext.Current.Session["foodRecipeId"] = food[0].FoodId;
                    var foodRecipeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["foodRecipeId"]);

                    System.Web.HttpContext.Current.Session["recipeName"] = model.RecipeName;

                    //var recipe = context.Recipe.Where(x => x.RecipeName.Equals(model.RecipeName)).ToList();

                    //if(recipe.Count > 0)
                    //{
                    //    ViewBag.RecipeAlreadyInDb = 1;

                    //}
                    if (ModelState.IsValid)
                    {
                        int recordsCreated = db.addRecipeDb(model.RecipeName, model.ServingSize, foodRecipeId, userId);

                        var ingredientData = getIngredientsForARecipe(model.RecipeName);

                        return View("_CreateRecipeReadonly", ingredientData);
                    }
                }
            }

            return View();
        }

        public ICollection getRecipeData()
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();

            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"]).GroupBy(x => x.RecipeName).Select(x => x.FirstOrDefault()).ToList();

            return ingredientsData;

        }

        public ICollection getIngredients()
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();


            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"]).GroupBy(x => x.RecipeName).Select(x => x).SelectMany(x => x).ToList();

            return ingredientsData;

        }

        public ICollection getIngredientsForARecipe(string nume)
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,
                          h.ServingSize,
                          h.FoodId,
                          h.RecipeId
                      })
                    .Join(context.Food, h => h.FoodId, f => f.FoodId, (h, f) => new MyRecipesViewModel
                    {
                        RecipeId = h.RecipeId,
                        RecipeName = h.RecipeName,
                        UserInformationId = h.UserInformationId,
                        ServingSize = h.ServingSize,
                        FoodId = f.FoodId,
                        FoodName = f.FoodName,
                        Calories = f.Calories,
                        Protein = f.Protein,
                        Carbs = f.Carbs,
                        Fat = f.Fat
                    }).ToList();


            var ingredientsData = query.Where(x => x.UserInformationId == (int)Session["userId"] && x.RecipeName == nume).GroupBy(x => x.RecipeName).Select(x => x).SelectMany(x => x).ToList();

            return ingredientsData;

        }

        public ICollection getLastRecipeIngredients(Recipe model)
        {
            var query = context.Recipe
                    .Join(context.UserInformation, h => h.UserInformationId,
                      i => i.UserInformationId, (h, i) => new
                      {
                          i.UserInformationId,
                          h.RecipeName,

healthyhams.Web/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using healthyhams.Data;
using healthyhams.Data.Models;
using healthyhams.Data.Services;
using healthyhams.Web.Models;

namespace healthyhams.Web.Controllers
{
    public class SignUpController : Controller
    {
        private readonly IUserData db;

        private readonly healthyhamsContext context;

        public SignUpController(IUserData db, healthyhamsContext context)
        {
            this.db = db;
            this.context = context;
        }

        public ActionResult Index()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(SignUpViewModel model)
        {
            Boolean status = context.Credentials.Any(x => x.Email == model.Email);

            if (status == true)
            {
                ViewBag.SignUpStatus = 1;
            }
            else
            {
                if (ModelState.IsValid)
                {
                    int recordsCreated = db.addCredentials(model.Email, model.Password);
                    return RedirectToAction("Index", "Survey");

                }
            }

            return View();

        }
    }
}

healthyhams.Web/Views/Home/Index.cshtml
@model IEnumerable<healthyhams.Data.RecipeApiModel>

@{
    ViewData["Title"] = "Home";
}

<head>
    <link rel="stylesheet" href="~/Content/css/Home.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="~/Content/media/logo.png" alt="Logo" height="100" width="150" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("About", "Index", "About", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Log in", "Index", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
    <div class="container-homepage">
        <h1>healthyhams</h1>
        <h2>for you to live better</h2>
        <p>track your diet with ease</p>

        <input class="button" type="button" value="SIGN UP" onclick="location.href='@Url.Action("Index", "SignUp")'" />
    </div>

    @*@if (Model != null)
    {
        foreach (var recipe in Model)
        {
            <div class="block-recipes">
                <div>@recipe.Id</div>
                <div>@recipe.Title</div>
                <img src="@recipe.Picture" alt="picture" />
            </div>
        }
    }*@

</body>

healthyhams.Web/Views/Home/Recipe.cshtml
@model IEnumerable<healthyhams.Data.RecipeApiModel>
@*@model IEnumerable<healthyhams.Web.Models.HomeViewModel>*@
@{
    ViewData["Title"] = "Home";
}

<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>

    <link rel="stylesheet" href="~/Content/css/UserRecipe.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("User", "Home")"><img src="~/Content/media/logo.png" alt="Logo" height="100" width="150" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("Journal", "Index", "Journal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My Recipes", "Index", "MyRecipes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Account", "Index", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal recipes-container">

            @if (Model != null)
            {
                foreach (var recipe in Model)
                {
                    <div class="card-container">
                        <div class="card u-clearfix">
                            <div class="card-body">
                                <span class="card-number card-circle subtle">@recipe.Id</span>
                                @*<span class="card-author subtle">John Smith</span>*@
                                <h2 class="card-title">@recipe.Title</h2>
                                @*<span class="card-description subtle">@recipe.Instructions</span>*@
                                @*<div class="card-read">Read</div>*@
                                @*<input type="button" value="Read" class="card-read" onclick="location.href='@Url.Action("Recipe", "Home", new {id = recipe.Id})'" />*@
                                @*<span class="card-tag card-circle subtle">C</span>*@
                            </div>
                            <img src=@recipe.Picture alt="" class="card-media" />
                            <span class="card-description subtle instructions-title">Instructions</span>
                            <span class="card-description subtle instructions">@recipe.Instructions</span>
                            @*<span class="card-description subtle tags">Tags: @recipe.Tags</span>*@
                        </div>
                        <div class="card-shadow"></div>
                    </div>

                    <!--<div class="card-container-info">
                        <div class="card u-clearfix">
                            <div class="card-body">
                                <span class="card-description subtle">Instructions</span>
                                <span class="card-description subtle">@recipe.Instructions</span>
                                <span class="card-description subtle">Tags: @recipe.Tags</span>-->
                                @*<div class="card-read">Read</div>*@
                                @*<input type="button" value="Read" class="card-read" onclick="location.href='@Url.Action("Recipe", "Home", new {id = recipe.Id})'" />*@
                                @*<span class="card-tag card-circle subtle">C</span>*@
                            <!--</div>
                        </div>
                        <div class="card-shadow"></div>
                    </div>-->
                }
            }

        </div>


    }
</body>

healthyhams.Web/Views/Home/User.cshtml
@model IEnumerable<healthyhams.Data.RecipeApiModel>
@*@model IEnumerable<healthyhams.Web.Models.HomeViewModel>*@
@{
    ViewData["Title"] = "Home";
}

<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.0.min.js"></script>

    <link rel="stylesheet" href="~/Content/css/User.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("User", "Home")"><img src="~/Content/media/logo.png" alt="Logo" height="100" width="150" /></a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("Journal", "Index", "Journal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My Recipes", "Index", "MyRecipes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Account", "Index", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <script>
        $(document).ready(function () {
            $('input[type="radio"]').click(function () {
                if ($(this).attr('id') == 'category') {

                    $('#label-category').show();
                    $('#Category').show();
                }
                else {
                    $('#label-category').hide();
                    $('#Category').hide();
                }

                if ($(this).attr('id') == 'area') {

                    $('#label-area').show();
                    $('#Area').show();
                }
                else {
                    $('#label-area').hide();
                    $('#Area').hide();
                }

                if ($(this).attr('id') == 'ingredient') {

                    $('#label-ingredient').show();
                    $('#Ingredient').show();
                }
                else {
                    $('#label-ingredient').hide();
                    $('#Ingredient').hide();
                }
            });
        });
    </script>

    <script>
        $(function () {
            var availableTags = [];
            $.ajax(
                {
                    type: 'GET',
                    url: '/Home/getAllCategories',
                    success: function (response) {
                        $.each(response, function (key, item) {
                            availableTags.push(item.Category)
                        });
                    }
                });

            $("#Category").autocomplete({
                source: availableTags
            });
        });

        $(function () {
            var availableTags = [];
            $.ajax(
                {
                    type: 'GET',
                    url: '/Home/getAllAreas',
                    success: function (response) {
                        $.each(response, function (key, item) {
                            availableTags.push(item.Area)
                        });
                    }
                });

            $("#Area").autocomplete({
                source: availableTags
            });
        });

        $(function () {
            var availableTags = [];
            $.ajax(
                {
                    type: 'GET',
                    url: '/Home/getAllIngredients',
                    success: function (response) {
                        $.each(response, function (key, item) {
                            availableTags.push(item.Ingredient)
                        });
                    }
                });

            $("#Ingredient").autocomplete({
                source: availableTags
            });
        });



    </script>
</header>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal recipes-container">
            <div class="form-group row">
                <label for="SearchType" name="searchType" id="searchType" class="control-label col-sm-3">Search By:</label>
                <div class="group">
                    @*<select name="SearchType" id="SearchType">
                <option value="default"></option>
                <option value="category">Category</option>
                <option value="area">Area</option>
                <option value="ingredient">Ingredient</option>
            </select>*@
                    <input type="radio" id="category" name="searchType" value="Category">
                    <label for="category">Category</label><br>

                    <input type="radio" id="area" name="searchType" value="Area">
                    <label for="area">Area</label><br>

                    <input type="radio" id="ingredient" name="searchType" value="Ingredient">
                    <label for="ingredient">Ingredient</label><br>
                </div>

                <div class="group  Category">
                    <label for="Category" id="label-category" name="searchTermCategory" class="control-label col-sm-3" style='display:none'>Category:</label>
                    <input type="text" id="Category" name="searchTermCategory" style='display:none'>
                </div>

                <div class="group Area">
                    <label for="Area" id="label-area" name="searchTermArea" class="control-label col-sm-3" style='display:none'>Area:</label>
                    <input type="text" id="Area" name="searchTermArea" style='display:none'>
                </div>

                <div class="group Ingredient">
                    <label for="Ingredient" id="label-ingredient" name="searchTermIngredient" class="control-label col-sm-3" style='display:none'>Ingredient:</label>
                    <input type="text" id="Ingredient" name="searchTermIngredient" style='display:none'>
                </div>

                <input type="submit" value="Search" class="button" />

            </div>


            @*@if (Model != null)
                {
                    foreach (var recipe in Model)
                    {
                        <div class="block-recipes">
                            <div>@recipe.Id</div>
                            <div>@recipe.Title</div>
                            <img src="@recipe.Picture" alt="picture" />
                        </div>
                    }
                }*@

            @if (Model != null)
            {
                foreach (var recipe in Model)
                {
                    <div class="card-container">
                        <div class="card u-clearfix">
                            <div class="card-body">
                                <span class="card-number card-circle subtle">@recipe.Id</span>
                                @*<span class="card-author subtle">John Smith</span>*@
                                <h2 class="card-title">@recipe.Title</h2>
                                @*<span class="card-description subtle">These last few weeks I have been working hard on a new brunch recipe for you all.</span>*@
                                <div class="card-read"></div>
                            <input type="button" value="Read" class="card-read" onclick="location.href='@Url.Action("Recipe", "Home", new {id = recipe.Id})'" />
                                @*<span class="card-tag card-circle subtle">C</span>*@
                            </div>
                            <img src=@recipe.Picture alt="" class="card-media" />
                        </div>
                        <div class="card-shadow"></div>
                    </div>
                }
            }


        </div>
    }
</body>